name: Update Schema

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  regen-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with: { fetch-depth: 0 }

      - name: Setup Deno
        uses: ./.github/actions/setup-deno

      - name: Regenerate schema
        run: deno task schema

      - name: Commit schema updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate labels schema"
          file_pattern: .github/labels.schema.json
